---
AWSTemplateFormatVersion: 2010-09-09
Parameters:
    AppsDomain:
        Description: Base domain shared between all apps
        Type: String
    AppsDomainSSLCertificate:
        Type: String
        Description: ARN of AWS Certificate Manager certificate for *.{AppsDomain}
    Route53HostedZoneId:
        Description: ID for the Route53 Hosted Zone which will hold the CNAME for this app
        Type: String
    AppName:
        Default: https_demo_be
        Type: String

Resources:
    AppSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Limit access to the app instances
            SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: 8443
              ToPort: 8443
              SourceSecurityGroupId: !GetAtt [ElbSecurityGroup, GroupId]

    AppScalingGroup:
        Type: AWS::AutoScaling::AutoScalingGroup
        Properties:
            AvailabilityZones: !GetAZs
            LaunchConfigurationName: !Ref AppLaunchConfig
            DesiredCapacity: 1
            MinSize: 0
            MaxSize: 2
            LoadBalancerNames:
            - !Ref ElasticLoadBalancer
        UpdatePolicy:
            AutoScalingRollingUpdate:
                MinInstancesInService: 1
                MaxBatchSize: 1

    AppLaunchConfig:
        Type: AWS::AutoScaling::LaunchConfiguration
        Properties:
        Properties:
            ImageId: ami-a4d44ed7
            SecurityGroups:
            - !GetAtt [AppSecurityGroup, GroupId]
            InstanceType: t2.nano
            UserData:
                !Base64 |
                    #cloud-config
                    ---
                    packages:
                    - git
                    - python-pip
                    - stunnel4
                    write_files:
                    - content: |
                        from flask import Flask
                        app = Flask(__name__)


                        @app.route("/")
                        def hello():
                            return "Hello World!"

                        if __name__ == "__main__":
                            app.run(port=8080)
                      path: /etc/hello.py
                      permissions: '0644'
                    - content: |
                        -----BEGIN PRIVATE KEY-----
                        MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDWsJ8FCfVKDVD3
                        sVtC6zTySE3eTUipCfn5XLyu9Us4QgWHPCBwq01DnMYQMRM5iTTCoXrnU4Ky8k7O
                        SUzmguAgbkHUSucsLfJzUVjCbxGEL0hJhPlOhTL+AMBVSMoepkUfbHJL95+ilEDH
                        lwNPLVCqBdlSs9WdPpeeJu2xmIHiqJecuXLchbdFfOvSQN1sW9ZvwLrNPUZZTWoD
                        Ji2viAddW6VOXFAJoT8X8h+2mUfMKZ2xeufMnsZ3s7xkLdHPO55luaa+mlJJluy3
                        quXjvM/Z4iqAolf7FT/ZzACo+JgeNzsdJYZEzVQ4Yp5sOZDmoT4zTMxVtMhKupXp
                        iNhPMKOJAgMBAAECggEAVtb4a6RciIicYKRnwsi7EOl4PdxK8L0tVNVTKP3lYCss
                        a0hB4vEXfqrSXshK+3HpWnTQ7vMToehrQfvaVD9KAzQ2AnYNzgwDzutvmK4uiqZJ
                        ehuEcGNmfeG16olX4E/nE8/c56eQ9cU78r+9wfAVecCF6HL/i+w+jeU3Lif/GbvU
                        b8C8PqowPeI5NEOIsq+mfW+bXdbB0xhMO7GIw9ew+kQIVHULpm3DNq1ScE+YCFDl
                        lJBlMvs6BMr1IQ8oehuxK3RpbxZDOcHZMtt0qC0qzZoRPxXxvxw/gEq12oMEaeoc
                        XD9lBLpU+XdlsjKg4RdF0U1ER2K0IHGpMbBS5Q6lBQKBgQDuqan1BppOnKJSBwbU
                        77lITMhzaAVTzx/IH2Bta/dP6N9VEohhOZRjlQmtHSBtdBpdS6zxmFsZx9/xeD20
                        pGZPWBztXNqdFyS1ynmVpafYiwW3eUSXQgLhHPZJN+PHGwhlZCHp/8JGLqZyv+57
                        ZU1YAGwEE9drKxzax2ekSwroFwKBgQDmSSRoqdSq0dWKIo7wUCG32rvbONBjURgO
                        JVit6WvqR96lWLzSiDn1phzTnkV21BYb7ZLrp6wWS/G2CvajD3agwDR3mj7taSwV
                        y75oiJ34s25v6HYv2LzIcGMfwWuCSda/88A9bRjx0mpkibVF0A0JS/dkwQAkyFZb
                        31EgL751XwKBgQCmOgmkHZswEayE0VwSx30XPFOI/fRn8SVDr4br73zrbVjP2f6f
                        KQmPami46EaDtY//Vwv3oZQiGrKBbqwbuz1/GfHb6QZiz5HEBGg2sJB9JCcxKQd7
                        CoES5acsS/8b2Fo6tEliv75CP4+y8LdbvqzmFDUnieJKRFbukmA/b/0CtQKBgBIi
                        hmx7m1TMa32SVSFVniIlZo/P/JElrLhIdqBTdn0fpcftogkOU0omB7UejKfb8dXH
                        Mr++F4418tX8LQoQSK5GFJuqmPQHSUJ6JgeDYrVYJAVKECyaa9t5BkVU7Qt4lyHM
                        p0HvGnzIrjo2ogDabnxh8ByOGl3LLQnVH0VinSQPAoGBAJmaXUu52r9b7T6gBL8d
                        CBlamtdwawkRl6U/5k8J8ukQ3cWC2h8yEyxZ9y0n59mOHz9KDHQ+w7+5wjZm7D/4
                        mCAqu/rZK6pEv6RgKEPEDMKTRZTqgrDkRkYdFUWgjZ7aeFX5zVkeed0ExyRO9oqS
                        5Vkyfn91sjRTk/fxnuU/KqQb
                        -----END PRIVATE KEY-----
                      path: /etc/stunnel/elb-backend-private.key
                      permissions: '0400'
                    - content: |
                        -----BEGIN CERTIFICATE-----
                        MIIDgzCCAmugAwIBAgIJAIMDqni6b9o4MA0GCSqGSIb3DQEBCwUAMFgxCzAJBgNV
                        BAYTAkdCMQ8wDQYDVQQIDAZMb25kb24xDzANBgNVBAcMBkxvbmRvbjEQMA4GA1UE
                        CgwHZXhhbXBsZTEVMBMGA1UEAwwMKi5iZW5tYWRlLml0MB4XDTE2MTEyMzEwMzg0
                        N1oXDTI2MTEyMTEwMzg0N1owWDELMAkGA1UEBhMCR0IxDzANBgNVBAgMBkxvbmRv
                        bjEPMA0GA1UEBwwGTG9uZG9uMRAwDgYDVQQKDAdleGFtcGxlMRUwEwYDVQQDDAwq
                        LmJlbm1hZGUuaXQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDWsJ8F
                        CfVKDVD3sVtC6zTySE3eTUipCfn5XLyu9Us4QgWHPCBwq01DnMYQMRM5iTTCoXrn
                        U4Ky8k7OSUzmguAgbkHUSucsLfJzUVjCbxGEL0hJhPlOhTL+AMBVSMoepkUfbHJL
                        95+ilEDHlwNPLVCqBdlSs9WdPpeeJu2xmIHiqJecuXLchbdFfOvSQN1sW9ZvwLrN
                        PUZZTWoDJi2viAddW6VOXFAJoT8X8h+2mUfMKZ2xeufMnsZ3s7xkLdHPO55luaa+
                        mlJJluy3quXjvM/Z4iqAolf7FT/ZzACo+JgeNzsdJYZEzVQ4Yp5sOZDmoT4zTMxV
                        tMhKupXpiNhPMKOJAgMBAAGjUDBOMB0GA1UdDgQWBBTC5njylCG4N5mY6AOJOZO8
                        GEylYjAfBgNVHSMEGDAWgBTC5njylCG4N5mY6AOJOZO8GEylYjAMBgNVHRMEBTAD
                        AQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAHj7OURmHmE5tgO9vI8rHWJDNJJdoYBvPy
                        sLDnAETmNHKVyH4Y6cOR6a392H3/HgCM4twJgAwiM+QXLd/0aVqLwx/x2NJiOi+W
                        nZQF7RmJq6an9B6o67fUX5rdN4vC11dr+SYTIy30ugfSqh8+KYPNzOvD2jLSoGiX
                        sEqhfsuR+h8ceKF29lCc2tQfy7olaKDAIOmAQ0xPDoVwS9l3XSIrZw+6B47Teasq
                        wKNHgqzf0DuJhbjYHmC4vV97uBai1eZcYfLHTf4na5TQoy/VZ3OesxDq7fDaU1sT
                        7byBMidCOug8J4nNTTVoE8HjlKXGjtujAfy/xD7dzMlWnRE8KhmS
                        -----END CERTIFICATE-----
                      path: /etc/stunnel/elb-backend-cert.pem
                      permissions: '0444'
                    - content: |
                        output=/var/log/stunnel-elb-backend.log
                        pid=/var/run/stunnel4/elb-backend.pid
                        setuid=stunnel4
                        setgid=stunnel4
                        client=no

                        [ELB]
                        cert=/etc/stunnel/elb-backend-cert.pem
                        key=/etc/stunnel/elb-backend-private.key
                        accept=0.0.0.0:8443
                        connect=127.0.0.1:8080
                      path: /etc/stunnel/elb-backend.conf
                      permissions: '0644'
                    runcmd:
                    - pip install flask gunicorn gevent
                    - sed -i 's/^ENABLED=0/ENABLED=1/' /etc/default/stunnel4
                    - touch /var/log/stunnel-elb-backend.log
                    - chown stunnel4 /var/log/stunnel-elb-backend.log /etc/stunnel/elb-backend-private.key /etc/stunnel/elb-backend-cert.pem
                    - systemctl restart stunnel4
                    - cd /etc/ && gunicorn hello:app -b 127.0.0.1:8080 -k gevent

    Route53RecordSet:
        Type: AWS::Route53::RecordSet
        Properties:
            HostedZoneId: !Ref Route53HostedZoneId
            Comment: !Ref AppName
            Name: !Join [ ".", [ !Ref AppName, !Ref AppsDomain, ""]]
            Type: CNAME
            TTL: 60
            ResourceRecords:
            - !GetAtt [ ElasticLoadBalancer, DNSName ]

    ElbSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Limit access to the ELB
            SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: 80
              ToPort: 80
              CidrIp: 0.0.0.0/0
            - IpProtocol: tcp
              FromPort: 443
              ToPort: 443
              CidrIp: 0.0.0.0/0

    ElasticLoadBalancer:
        Type: AWS::ElasticLoadBalancing::LoadBalancer
        Properties:
            AvailabilityZones: !GetAZs
            CrossZone: true
            Listeners:
            - LoadBalancerPort: 80
              InstancePort: 8443
              Protocol: HTTP
              InstanceProtocol: HTTPS
            - LoadBalancerPort: 443
              InstancePort: 8443
              Protocol: HTTPS
              InstanceProtocol: HTTPS
              SSLCertificateId: !Ref AppsDomainSSLCertificate
              PolicyNames: []
            HealthCheck:
                Target: "TCP:8443"
                HealthyThreshold: "3"
                UnhealthyThreshold: "5"
                Interval: "6"
                Timeout: "5"
            SecurityGroups:
            - !GetAtt [ElbSecurityGroup, GroupId]
            Policies:
            - PolicyName: BackendPublicKeyPolicy
              PolicyType: PublicKeyPolicyType
              Attributes:
              - Name: PublicKey
                Value: |
                    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1rCfBQn1Sg1Q97FbQus0
                    8khN3k1IqQn5+Vy8rvVLOEIFhzwgcKtNQ5zGEDETOYk0wqF651OCsvJOzklM5oLg
                    IG5B1ErnLC3yc1FYwm8RhC9ISYT5ToUy/gDAVUjKHqZFH2xyS/efopRAx5cDTy1Q
                    qgXZUrPVnT6XnibtsZiB4qiXnLly3IW3RXzr0kDdbFvWb8C6zT1GWU1qAyYtr4gH
                    XVulTlxQCaE/F/IftplHzCmdsXrnzJ7Gd7O8ZC3RzzueZbmmvppSSZbst6rl47zP
                    2eIqgKJX+xU/2cwAqPiYHjc7HSWGRM1UOGKebDmQ5qE+M0zMVbTISrqV6YjYTzCj
                    iQIDAQAB
            - PolicyName: BackendServerAuthenticationPolicy
              PolicyType: BackendServerAuthenticationPolicyType
              Attributes:
              - Name: PublicKeyPolicyName
                Value: BackendPublicKeyPolicy
              InstancePorts: [ "8443" ]

Outputs:
    LoadBalancer:
        Value: !Join [ ".", [ !Ref AppName, !Ref AppsDomain ]]
